abc.ru:
  - [А, а]
  - [К, к]
  - [Х, х]
  - [Б, б]
  - [Л, л]
  - [Ц, ц]
  - [В, в]
  - [М, м]
  - [Ч, ч]
  - [Г, г]
  - [Н, н]
  - [Ш, ш]
  - [Д, д]
  - [О, о]
  - [Щ, щ]
  - [Е, е]
  - [П, п]
  - [Ъ, ъ]
  - [Ё, ё]
  - [Р, р]
  - [Ы, ы]
  - [Ж, ж]
  - [С, с]
  - [Ь, ь]
  - [З, з]
  - [Т, т]
  - [Э, э]
  - [И, и]
  - [У, у]
  - [Ю, ю]
  - [Й, й]
  - [Ф, ф]
  - [Я, я]